### PR TITLE
Update Odoo OCB to the latest version

### PR DESCRIPTION
**Pull request by seb-elico**

### CODE REVIEW

**Comment by duanyp1991** [comment]
LGTM

**Comment by elicoidal** [comment]
LGTM.
I think this kind of request should be fast-tracked

**Comment by seb-elico** [comment]
Agreed. Though soon it won't go through PR as it will be managed by a script with auto-deployment.

**Comment by elicoidal** [comment]
my comment was a general one: some PR can be fast tracked (very simple/obvious or descriptions etc.)

to be decided which ones with simple rule

**Pull request merged**
