### PR TITLE
update 10.0

### PR DESCRIPTION
**Pull request by noahzaozao**

### CODE REVIEW

**Comment by noahzaozao** [comment]
@elicoidal @seb-elico Please check this PR for 10.0

**Comment by elicoidal** [comment]
@noahzaozao we should not mention OCB for v10.0 following community decision to discontinue the project.
Other than that LGTM

**Comment by noahzaozao** [comment]
@elicoidal Sorry I didn't get your point

**Comment by elicoidal** [comment]
@noahzaozao I am talking about "OCB_COMMIT_ID" probably should be migrated to ODOO_COMMIT_ID

**Comment by noahzaozao** [comment]
@elicoidal Okay , I'll confirm this with @seb-elico

**Comment by seb-elico** [comment]
LGTM
@elicoidal agreed, `OCB_COMMIT_ID` should be renamed to `ODOO_COMMIT_ID` and store a commit ID of https://github.com/odoo/odoo rather than https://github.com/OCA/OCB, but on top of that we need to change the Git repo URL in the Dockerfile and update accordingly the cron job that triggers the nightly build. I will handle all that in a new PR, but IMO no need to delay this PR since we urgently need a v10 image

**Pull request merged**
