### PR TITLE
missing 'POSTGRES_DB=postgres' to docker-compose.yml example

### PR DESCRIPTION
**Pull request by patleb**
It might be needed for other examples, but I didn't test other scenarios yet.

### CODE REVIEW

**Comment by patleb** [comment]
Related to this issue https://github.com/Elico-Corp/odoo-docker/issues/123.

**Comment by elicoidal** [comment]
@seb-elico ?

**Comment by seb-elico** [comment]
@patleb 
Thanks for the suggestion. If I'm correct, this is the default value. We have never used it and it works fine, so not necessary IMO. Closing this issue, feel free to provide more details though!

CC @elicoidal

**Comment by patleb** [comment]
I'm using postgres 11 and odoo 12 on ubuntu and it was for the introductory example where there is not much configuration. Also, if you create a specific db user for odoo (as suggested in the other examples), you won't have this issue.

I merely applied the solution suggested [here](https://www.odoo.com/forum/help-1/question/docker-keyerror-ir-http-141315) and this is pretty much the same behavior for the issue https://github.com/Elico-Corp/odoo-docker/issues/123. So, unless you know what the issue was about, I'm quite sure that this was the same problem brought up.

Also, `postgres` might be the default db name, but I'm guessing that the recent images of postgres don't differentiate when the config is missing (which suggests that it might be mandatory or a bug has been introduced recently).

I don't really mind that you close the PR, I was just sharing what I did to make your docker-compose.yml example work on my side.

**Pull request closed without merging**
